version: "3.9"

services:
  postgresdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: forum
    ports:
      - 5432:5432