version: '3.9'

services:
    db:
        image: postgres:latest
        restart: always
        ports:
            - 8081:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: postgres
